### ISSUE TITLE
기능: 회원가입

### ISSUE THREAD

**Issue by jeongbaebang** [jeongbaebang/musubi-back#5]
### 작업 리스트
- [x] #6 Auth에 대한 모듈, 컨트롤러, 서비스 생성
- [x] #7 user를 위한 Entity 생성
- [x] #8 Repository 생성 & DB 연결
- [x] #9 DTO 작업 & 유효성 작업
- [x] #10 에러 처리 핸들링
- [x] #11 유저 칼럼 중복 제거 작업 (유니크)
- [x] #12 비밀번호 암호화 작업 (bcrypt)
